pub mod app;
pub mod archive;
pub mod categories;
pub mod coach;
pub mod config;
pub mod copy;
pub mod currency;
pub mod data;
pub mod doctor;
pub mod export;
pub mod graph;
pub mod ingest;
pub mod ingest_cache;
pub mod keymap;
pub mod mcp;
pub mod models;
pub mod overview;
pub mod pricing;
#[cfg(feature = "quota-sync")]
pub mod quota_sync;
pub mod reports;
pub mod runtime;
pub mod search;
#[cfg(feature = "quota-sync")]
pub mod secrets;
pub mod theme;
pub mod tools;
pub mod ui;
